In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array((1,6,3,4,9))
print(a)
print(b)

[1 2 3 4 5]
[1 6 3 4 9]


In [12]:
a = np.array([1,2,3,5,7], dtype='i')


In [11]:
b = np.array((2,3,5), dtype='f')

In [5]:
print(a)

[1 2 3 5 7]


In [9]:
type(b)

numpy.ndarray

In [13]:
b.dtype

dtype('float32')

In [14]:
a = np.array([1,2,3],[4,5,6])
print(a.ndim)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [15]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [16]:
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(b.ndim)

3


In [17]:
a = np.array([[1,2,3], [4,5,6]])

In [18]:
a.ndim

2

In [19]:
a[1,0]

4

In [20]:
a[0,1]

2

In [21]:
b = np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])

In [22]:
b[1,1,1]

55

In [23]:
b[0,1,0]

4

In [24]:
b = np.array([[3,5,2,42],[6,3,8,45]])

In [25]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [26]:
c.ndim

3

In [27]:
c[0,2,2]

-1

In [28]:
c.shape


(2, 3, 3)

In [29]:
cc = np.array([[[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]],[[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]]])

In [30]:
cc.ndim


4

In [31]:
cc.shape

(2, 2, 3, 3)

In [32]:
c.size - cc.size

-18

In [33]:
cc.size

36

In [34]:
cc.nbytes

144

In [35]:
cc.itemsize

4

In [36]:
d = np.arange(150)

In [37]:
d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [39]:
for i in np.arange(30):
    a = i*2
    print(a)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58


In [40]:
x = np.random.permutation(np.arange(30))
x

array([ 9, 10,  7, 19, 26, 22, 25,  0,  4, 20, 13, 24, 18, 12, 17,  1,  5,
        6, 21,  2, 23, 15, 14, 28,  3,  8, 27, 16, 11, 29])