In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array((1,6,3,4,9))
print(a)
print(b)

[1 2 3 4 5]
[1 6 3 4 9]


In [12]:
a = np.array([1,2,3,5,7], dtype='i')


In [11]:
b = np.array((2,3,5), dtype='f')

In [5]:
print(a)

[1 2 3 5 7]


In [9]:
type(b)

numpy.ndarray

In [13]:
b.dtype

dtype('float32')

In [14]:
a = np.array([1,2,3],[4,5,6])
print(a.ndim)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [15]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [16]:
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(b.ndim)

3


In [17]:
a = np.array([[1,2,3], [4,5,6]])

In [18]:
a.ndim

2

In [19]:
a[1,0]

4

In [20]:
a[0,1]

2

In [21]:
b = np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])

In [22]:
b[1,1,1]

55

In [23]:
b[0,1,0]

4

In [24]:
b = np.array([[3,5,2,42],[6,3,8,45]])

In [25]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [26]:
c.ndim

3

In [27]:
c[0,2,2]

-1

In [28]:
c.shape


(2, 3, 3)

In [29]:
cc = np.array([[[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]],[[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]]])

In [30]:
cc.ndim


4

In [31]:
cc.shape

(2, 2, 3, 3)

In [32]:
c.size - cc.size

-18

In [33]:
cc.size

36

In [34]:
cc.nbytes

144

In [35]:
cc.itemsize

4

In [36]:
d = np.arange(150)

In [37]:
d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [39]:
for i in np.arange(30):
    a = i*2
    print(a)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58


In [40]:
x = np.random.permutation(np.arange(30))
x

array([ 9, 10,  7, 19, 26, 22, 25,  0,  4, 20, 13, 24, 18, 12, 17,  1,  5,
        6, 21,  2, 23, 15, 14, 28,  3,  8, 27, 16, 11, 29])

In [3]:
import numpy as np
c = np.random.rand(2,3,4,2)
c

array([[[[0.10419851, 0.84341018],
         [0.32915772, 0.87779414],
         [0.77816512, 0.96918809],
         [0.20020211, 0.17981231]],

        [[0.70569194, 0.67229037],
         [0.83770195, 0.89037417],
         [0.35977438, 0.39929573],
         [0.09708591, 0.66007447]],

        [[0.97923117, 0.94579575],
         [0.82055414, 0.8778464 ],
         [0.87745975, 0.65668321],
         [0.76394865, 0.20296579]]],


       [[[0.03954437, 0.08273987],
         [0.3296043 , 0.44442823],
         [0.83825527, 0.62058329],
         [0.9499455 , 0.72983773]],

        [[0.92408948, 0.8893241 ],
         [0.91708084, 0.790452  ],
         [0.4557837 , 0.5998258 ],
         [0.39492614, 0.69831428]],

        [[0.38364502, 0.97912478],
         [0.26206056, 0.59732147],
         [0.76342904, 0.7211286 ],
         [0.92587739, 0.12692646]]]])

In [4]:
c.ndim

4

In [5]:
d = np.arrange(100).reshape(4,25)

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
d = np.arange(100).reshape(4,25)

In [7]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
d.random.permutation()

AttributeError: 'numpy.ndarray' object has no attribute 'random'

In [9]:
d.ndim

2

In [10]:
d[1,8]

33

In [11]:
dd = np.random.permutation(d[3])

dd

array([86, 95, 99, 77, 89, 93, 78, 75, 97, 87, 82, 92, 88, 94, 91, 83, 76,
       81, 80, 84, 98, 79, 85, 96, 90])

In [12]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
np.random.permutation(d[3])

array([75, 87, 83, 96, 97, 99, 86, 78, 79, 88, 84, 89, 94, 95, 80, 77, 76,
       81, 91, 93, 92, 82, 90, 85, 98])

In [14]:
d = np.arange(100).reshape(4,5,5)
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [16]:
cc = d[0,1,2]
cc

7

In [17]:
cc = d[1,2]
cc = cc[1:4]
cc

array([36, 37, 38])

In [18]:
ccc = d[2]
ccc = ccc[1:5]

In [19]:
ccc

array([[55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [20]:
ccc = ccc.reshape(1,20)

In [21]:
ccc

array([[55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74]])

In [22]:
cc

array([36, 37, 38])

In [23]:
s

NameError: name 's' is not defined

In [24]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [25]:
d.shape

(4, 5, 5)

In [26]:
felipe = d.reshape(1,100)[14:91]

In [27]:
felipe

array([], shape=(0, 100), dtype=int32)

In [28]:
felipe = d.reshape(1,100)

In [29]:
felipe

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [30]:
felipe = felipe[0]


In [31]:
felipe

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
felipe = felipe[14:91]

In [33]:
felipe

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90])

In [34]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [35]:
x = d.reshape(1,100)

In [36]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [37]:
x = x[0]

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
x = x[::-1]
x

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [40]:
x = x[0:51]
x


array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49])

In [42]:
x = x[:50]
x

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

In [43]:
x = x[::2]

In [44]:
x

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51])

In [47]:
for number in x:
    number = number+1
    print(number)


100
98
96
94
92
90
88
86
84
82
80
78
76
74
72
70
68
66
64
62
60
58
56
54
52


In [46]:
print(x)

[99 97 95 93 91 89 87 85 83 81 79 77 75 73 71 69 67 65 63 61 59 57 55 53
 51]


In [48]:
x

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51])

In [62]:
xx = x[(x>60) & (x<100)]
xx

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61])

In [64]:
A = np.round(10*np.random.rand(2,3))
A

array([[6., 6., 4.],
       [4., 2., 1.]])

In [65]:
A+3

array([[9., 9., 7.],
       [7., 5., 4.]])

In [66]:
A+(np.arange(2).reshape(2,1))
A

array([[6., 6., 4.],
       [4., 2., 1.]])

In [67]:
B = np.round(10*np.random.rand(2,2))

In [68]:
B

array([[6., 8.],
       [9., 2.]])

In [69]:
C = np.hstack((A,B))

In [70]:
C

array([[6., 6., 4., 6., 8.],
       [4., 2., 1., 9., 2.]])

In [71]:
a = np.random.permutation(np.arange(10))
a

array([4, 3, 9, 5, 1, 2, 8, 6, 0, 7])

In [72]:
a = np.random.permutation(np.arange(10))
a

array([2, 4, 5, 0, 7, 6, 1, 3, 9, 8])

In [73]:
for range(10):
    print("a")

SyntaxError: cannot assign to function call (2508466491.py, line 1)

In [74]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [75]:
xxx = np.arange(3)

In [76]:
xxx

array([0, 1, 2])

In [102]:
xxx = np.random.permutation(np.arange(4))


while xxx[0] != 0 and xxx[3] != 3:
    print("before: " + str(xxx))
          
    xxx = np.random.permutation(xxx)
    print("after: " + str(xxx))
    

before: [1 2 3 0]
after: [2 0 3 1]
before: [2 0 3 1]
after: [2 1 0 3]


In [103]:
xxx = np.random.permutation(np.arange(40))
xxx

array([35,  9, 18, 12, 10,  6, 36,  8, 26, 34, 20, 17, 15, 21,  3, 23,  4,
       29, 13, 19, 30,  1, 38, 32,  7,  5, 27, 24,  2, 14, 22, 37, 16, 31,
       33, 39, 28, 11,  0, 25])

In [104]:
xxx = xxx.sort()
xxx

In [105]:
xxx

In [106]:
print(xxx)

None


In [107]:
xxx = np.random.permutation(np.arange(40))
xxx

array([ 0, 17,  5, 33, 39, 37, 27, 12, 14, 10, 32, 16, 20,  8, 31, 13, 21,
        4,  3,  7, 25,  9, 22, 11, 23, 26,  6, 18, 28, 30, 34, 38, 35,  2,
       15, 36,  1, 29, 19, 24])

In [108]:
xxx.sort()
xxx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [109]:
b = np.random.rand(5000)

b

array([0.08933434, 0.65877739, 0.60489451, ..., 0.5848769 , 0.75914087,
       0.60099193])

In [110]:
%timeit np.sum(b)
%timeit sum(b)

3.67 µs ± 5.04 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
266 µs ± 205 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [111]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s


In [112]:
%timeit mySum(b)

323 µs ± 1.75 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [113]:
import pandas as pd

In [114]:
print(pd.__version__)

2.0.3


In [116]:
a = pd.Series([2,3,4,5], index=['a','b','c','d'])
a

a    2
b    3
c    4
d    5
dtype: int64

In [117]:
type(a)

pandas.core.series.Series

In [118]:
type(a.values)

numpy.ndarray

In [119]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [120]:
a['b']

3

In [121]:
a['a':'c']

a    2
b    3
c    4
dtype: int64

In [124]:
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}

In [125]:
gradesPandas = pd.Series(grades_dict)

In [126]:
gradesPandas

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [127]:
grades_dict

{'A': 4, 'B': 3.5, 'C': 3, 'D': 2.5}

In [128]:
gradesPandas.values



array([4. , 3.5, 3. , 2.5])

In [129]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marksPandas = pd.Series(marks_dict)
marksPandas

A    85
B    75
C    65
D    55
dtype: int64

In [131]:
d = pd.DataFrame({"Marks":marksPandas,"Grades":gradesPandas})

In [132]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [133]:
d.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [134]:
dT = d.T 

In [135]:
dT
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [136]:
dT

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [137]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [138]:
dT.T

Marks  Grades
A   85.0     4.0
B   75.0     3.5
C   65.0     3.0
D   55.0     2.5

In [139]:
xxpd = np.arange(100).reshape(4,5,5)

xxpd

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [140]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [141]:
d[1,1]

KeyError: (1, 1)

In [142]:
d[2,0]

KeyError: (2, 0)

In [143]:
d.values[1,1]

3.5

In [144]:
d.columns

Index(['Marks', 'Grades'], dtype='object')

In [145]:
d['ScaledMarks'] = d['Marks']*0.9

In [146]:
d

Marks  Grades  ScaledMarks
A     85     4.0         76.5
B     75     3.5         67.5
C     65     3.0         58.5
D     55     2.5         49.5

In [147]:
del d['ScaledMarks']

In [148]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [1]:
d

NameError: name 'd' is not defined

In [2]:
import pandas as pd


In [3]:
pd.Series()

Series([], dtype: object)

In [4]:
import numpy as np

In [5]:
np.random.permutation(np.arange(50))

array([ 3, 46, 32, 41,  5, 40, 29, 35, 28,  7, 11,  0,  4, 44, 31, 17, 10,
       42, 33, 27, 30, 38, 43,  9, 25, 34, 15, 36, 39, 21, 26, 19, 18, 45,
       12, 23,  2, 16, 49, 24, 47, 22,  6,  1, 13,  8, 14, 37, 20, 48])

In [6]:
a = pd.DataFrame([{'a':1,'b':4}, {'b':-3, 'c':9}])

In [7]:
a

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [8]:
a.fillna('b')

a  b    c
0  1.0  4    b
1    b -3  9.0

In [9]:
a = pd.DataFrame([{'a':1,'b':4}, {'b':-3, 'c':9}])

In [10]:
a

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [11]:
a.dropna

<bound method DataFrame.dropna of      a  b    c
0  1.0  4  NaN
1  NaN -3  9.0>

In [12]:
a

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [13]:
a.dropna()

Empty DataFrame
Columns: [a, b, c]
Index: []

In [14]:
a

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [15]:
pd.dropna(a)

AttributeError: module 'pandas' has no attribute 'dropna'

In [16]:
np.dropna

AttributeError: module 'numpy' has no attribute 'dropna'

In [17]:
dropna(a)

NameError: name 'dropna' is not defined

In [18]:
a = pd.Series(['a','b','c'], index=[1,3,5])

In [19]:
a

1    a
3    b
5    c
dtype: object

In [20]:
a[1]

'a'

In [21]:
a[1:3]

3    b
5    c
dtype: object

In [22]:
a.loc[1:3]

1    a
3    b
dtype: object

In [23]:
&timethis a.iloc[1:3]

SyntaxError: invalid syntax (3945507911.py, line 1)

In [24]:
&timeit a.iloc[1:3]

SyntaxError: invalid syntax (547269425.py, line 1)

In [25]:
d

NameError: name 'd' is not defined

In [26]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marksPandas = pd.Series(marks_dict)
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
gradesPandas = pd.Series(grades_dict)
d = pd.DataFrame({"Marks":marksPandas,"Grades":gradesPandas})

In [27]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [28]:
d.loc[3]

KeyError: 3

In [29]:
d.iloc[3,2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [30]:
d.iloc[3,:]

Marks     55.0
Grades     2.5
Name: D, dtype: float64

In [31]:
from sklearn.impute import SimpleImputer

In [32]:
df = pd.read_csv("C:/Users/bielz/OneDrive/Documentos/GitHub/2024/January/covid_19_data.csv")

In [33]:
df

SNo ObservationDate                        Province/State  \
0        1      01/22/2020                                 Anhui   
1        2      01/22/2020                               Beijing   
2        3      01/22/2020                             Chongqing   
3        4      01/22/2020                                Fujian   
4        5      01/22/2020                                 Gansu   
...    ...             ...                                   ...   
4242  4243      03/08/2020                    Northern Territory   
4243  4244      03/08/2020  Lackland, TX (From Diamond Princess)   
4244  4245      03/08/2020                 Montgomery County, TX   
4245  4246      03/08/2020     Omaha, NE (From Diamond Princess)   
4246  4247      03/08/2020    Travis, CA (From Diamond Princess)   

      Country/Region          Last Update  Confirmed  Deaths  Recovered  
0     Mainland China      1/22/2020 17:00        1.0     0.0        0.0  
1     Mainland China      1/22/2020 17:00       14.0     0.0        0.0  
2     Mainland China      1/22/2020 17:00        6.0     0.0        0.0  
3     Mainland China      1/22/2020 17:00        1.0     0.0        0.0  
4     Mainland China      1/22/2020 17:00        0.0     0.0        0.0  
...              ...                  ...        ...     ...        ...  
4242       Australia  2020-03-06T04:33:03        0.0     0.0        0.0  
4243              US  2020-02-24T23:33:02        0.0     0.0        0.0  
4244              US  2020-03-07T19:53:02        0.0     0.0        0.0  
4245              US  2020-02-24T23:33:02        0.0     0.0        0.0  
4246              US  2020-02-24T23:33:02        0.0     0.0        0.0  

[4247 rows x 8 columns]

In [34]:
df2 = df.drop(['SNo','Last Update'], axis=1,inplace=True)
df2

In [35]:
df2

In [36]:
df

ObservationDate                        Province/State  Country/Region  \
0         01/22/2020                                 Anhui  Mainland China   
1         01/22/2020                               Beijing  Mainland China   
2         01/22/2020                             Chongqing  Mainland China   
3         01/22/2020                                Fujian  Mainland China   
4         01/22/2020                                 Gansu  Mainland China   
...              ...                                   ...             ...   
4242      03/08/2020                    Northern Territory       Australia   
4243      03/08/2020  Lackland, TX (From Diamond Princess)              US   
4244      03/08/2020                 Montgomery County, TX              US   
4245      03/08/2020     Omaha, NE (From Diamond Princess)              US   
4246      03/08/2020    Travis, CA (From Diamond Princess)              US   

      Confirmed  Deaths  Recovered  
0           1.0     0.0        0.0  
1          14.0     0.0        0.0  
2           6.0     0.0        0.0  
3           1.0     0.0        0.0  
4           0.0     0.0        0.0  
...         ...     ...        ...  
4242        0.0     0.0        0.0  
4243        0.0     0.0        0.0  
4244        0.0     0.0        0.0  
4245        0.0     0.0        0.0  
4246        0.0     0.0        0.0  

[4247 rows x 6 columns]

In [37]:
df.head()

ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [38]:
df.rename(columns={'ObservationDate':'Date', 'Province/State': 'Province', 'Country/Region': 'Country', 'Confirmed':'Cases'})

Date                              Province         Country  Cases  \
0     01/22/2020                                 Anhui  Mainland China    1.0   
1     01/22/2020                               Beijing  Mainland China   14.0   
2     01/22/2020                             Chongqing  Mainland China    6.0   
3     01/22/2020                                Fujian  Mainland China    1.0   
4     01/22/2020                                 Gansu  Mainland China    0.0   
...          ...                                   ...             ...    ...   
4242  03/08/2020                    Northern Territory       Australia    0.0   
4243  03/08/2020  Lackland, TX (From Diamond Princess)              US    0.0   
4244  03/08/2020                 Montgomery County, TX              US    0.0   
4245  03/08/2020     Omaha, NE (From Diamond Princess)              US    0.0   
4246  03/08/2020    Travis, CA (From Diamond Princess)              US    0.0   

      Deaths  Recovered  
0        0.0        0.0  
1        0.0        0.0  
2        0.0        0.0  
3        0.0        0.0  
4        0.0        0.0  
...      ...        ...  
4242     0.0        0.0  
4243     0.0        0.0  
4244     0.0        0.0  
4245     0.0        0.0  
4246     0.0        0.0  

[4247 rows x 6 columns]

In [39]:
df['Date'] = pd.to_datetime(df['Date'])
df.head()

KeyError: 'Date'

In [40]:
df['Date']= pd.to_datetime(df['Date'])

KeyError: 'Date'

In [41]:
print(df.columns)

Index(['ObservationDate', 'Province/State', 'Country/Region', 'Confirmed',
       'Deaths', 'Recovered'],
      dtype='object')


In [42]:
df

ObservationDate                        Province/State  Country/Region  \
0         01/22/2020                                 Anhui  Mainland China   
1         01/22/2020                               Beijing  Mainland China   
2         01/22/2020                             Chongqing  Mainland China   
3         01/22/2020                                Fujian  Mainland China   
4         01/22/2020                                 Gansu  Mainland China   
...              ...                                   ...             ...   
4242      03/08/2020                    Northern Territory       Australia   
4243      03/08/2020  Lackland, TX (From Diamond Princess)              US   
4244      03/08/2020                 Montgomery County, TX              US   
4245      03/08/2020     Omaha, NE (From Diamond Princess)              US   
4246      03/08/2020    Travis, CA (From Diamond Princess)              US   

      Confirmed  Deaths  Recovered  
0           1.0     0.0        0.0  
1          14.0     0.0        0.0  
2           6.0     0.0        0.0  
3           1.0     0.0        0.0  
4           0.0     0.0        0.0  
...         ...     ...        ...  
4242        0.0     0.0        0.0  
4243        0.0     0.0        0.0  
4244        0.0     0.0        0.0  
4245        0.0     0.0        0.0  
4246        0.0     0.0        0.0  

[4247 rows x 6 columns]

In [43]:
df.rename(columns={'ObservationDate':'Date', 'Province/State': 'Province', 'Country/Region': 'Country', 'Confirmed':'Cases'})
df

ObservationDate                        Province/State  Country/Region  \
0         01/22/2020                                 Anhui  Mainland China   
1         01/22/2020                               Beijing  Mainland China   
2         01/22/2020                             Chongqing  Mainland China   
3         01/22/2020                                Fujian  Mainland China   
4         01/22/2020                                 Gansu  Mainland China   
...              ...                                   ...             ...   
4242      03/08/2020                    Northern Territory       Australia   
4243      03/08/2020  Lackland, TX (From Diamond Princess)              US   
4244      03/08/2020                 Montgomery County, TX              US   
4245      03/08/2020     Omaha, NE (From Diamond Princess)              US   
4246      03/08/2020    Travis, CA (From Diamond Princess)              US   

      Confirmed  Deaths  Recovered  
0           1.0     0.0        0.0  
1          14.0     0.0        0.0  
2           6.0     0.0        0.0  
3           1.0     0.0        0.0  
4           0.0     0.0        0.0  
...         ...     ...        ...  
4242        0.0     0.0        0.0  
4243        0.0     0.0        0.0  
4244        0.0     0.0        0.0  
4245        0.0     0.0        0.0  
4246        0.0     0.0        0.0  

[4247 rows x 6 columns]

In [44]:
df.rename(columns={'ObservationDate':'Date', 'Province/State': 'Province', 'Country/Region': 'Country', 'Confirmed':'Cases'}, inplace=True)

In [45]:
df

Date                              Province         Country  Cases  \
0     01/22/2020                                 Anhui  Mainland China    1.0   
1     01/22/2020                               Beijing  Mainland China   14.0   
2     01/22/2020                             Chongqing  Mainland China    6.0   
3     01/22/2020                                Fujian  Mainland China    1.0   
4     01/22/2020                                 Gansu  Mainland China    0.0   
...          ...                                   ...             ...    ...   
4242  03/08/2020                    Northern Territory       Australia    0.0   
4243  03/08/2020  Lackland, TX (From Diamond Princess)              US    0.0   
4244  03/08/2020                 Montgomery County, TX              US    0.0   
4245  03/08/2020     Omaha, NE (From Diamond Princess)              US    0.0   
4246  03/08/2020    Travis, CA (From Diamond Princess)              US    0.0   

      Deaths  Recovered  
0        0.0        0.0  
1        0.0        0.0  
2        0.0        0.0  
3        0.0        0.0  
4        0.0        0.0  
...      ...        ...  
4242     0.0        0.0  
4243     0.0        0.0  
4244     0.0        0.0  
4245     0.0        0.0  
4246     0.0        0.0  

[4247 rows x 6 columns]

In [46]:
df["Date"] = pd.to_datetime(df["Date"])

In [47]:
df

Date                              Province         Country  Cases  \
0    2020-01-22                                 Anhui  Mainland China    1.0   
1    2020-01-22                               Beijing  Mainland China   14.0   
2    2020-01-22                             Chongqing  Mainland China    6.0   
3    2020-01-22                                Fujian  Mainland China    1.0   
4    2020-01-22                                 Gansu  Mainland China    0.0   
...         ...                                   ...             ...    ...   
4242 2020-03-08                    Northern Territory       Australia    0.0   
4243 2020-03-08  Lackland, TX (From Diamond Princess)              US    0.0   
4244 2020-03-08                 Montgomery County, TX              US    0.0   
4245 2020-03-08     Omaha, NE (From Diamond Princess)              US    0.0   
4246 2020-03-08    Travis, CA (From Diamond Princess)              US    0.0   

      Deaths  Recovered  
0        0.0        0.0  
1        0.0        0.0  
2        0.0        0.0  
3        0.0        0.0  
4        0.0        0.0  
...      ...        ...  
4242     0.0        0.0  
4243     0.0        0.0  
4244     0.0        0.0  
4245     0.0        0.0  
4246     0.0        0.0  

[4247 rows x 6 columns]

In [48]:
c

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4247 entries, 0 to 4246
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   Date       4247 non-null   datetime64[ns]
 1   Province   2746 non-null   object        
 2   Country    4247 non-null   object        
 3   Cases      4247 non-null   float64       
 4   Deaths     4247 non-null   float64       
 5   Recovered  4247 non-null   float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 199.2+ KB


In [49]:
df = df.fillna('NA')

In [50]:
df.info

<bound method DataFrame.info of            Date                              Province         Country  Cases  \
0    2020-01-22                                 Anhui  Mainland China    1.0   
1    2020-01-22                               Beijing  Mainland China   14.0   
2    2020-01-22                             Chongqing  Mainland China    6.0   
3    2020-01-22                                Fujian  Mainland China    1.0   
4    2020-01-22                                 Gansu  Mainland China    0.0   
...         ...                                   ...             ...    ...   
4242 2020-03-08                    Northern Territory       Australia    0.0   
4243 2020-03-08  Lackland, TX (From Diamond Princess)              US    0.0   
4244 2020-03-08                 Montgomery County, TX              US    0.0   
4245 2020-03-08     Omaha, NE (From Diamond Princess)              US    0.0   
4246 2020-03-08    Travis, CA (From Diamond Princess)              US    0.0   

      D

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4247 entries, 0 to 4246
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   Date       4247 non-null   datetime64[ns]
 1   Province   4247 non-null   object        
 2   Country    4247 non-null   object        
 3   Cases      4247 non-null   float64       
 4   Deaths     4247 non-null   float64       
 5   Recovered  4247 non-null   float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 199.2+ KB


In [52]:
df.head(10)

Date   Province         Country  Cases  Deaths  Recovered
0 2020-01-22      Anhui  Mainland China    1.0     0.0        0.0
1 2020-01-22    Beijing  Mainland China   14.0     0.0        0.0
2 2020-01-22  Chongqing  Mainland China    6.0     0.0        0.0
3 2020-01-22     Fujian  Mainland China    1.0     0.0        0.0
4 2020-01-22      Gansu  Mainland China    0.0     0.0        0.0
5 2020-01-22  Guangdong  Mainland China   26.0     0.0        0.0
6 2020-01-22    Guangxi  Mainland China    2.0     0.0        0.0
7 2020-01-22    Guizhou  Mainland China    1.0     0.0        0.0
8 2020-01-22     Hainan  Mainland China    4.0     0.0        0.0
9 2020-01-22      Hebei  Mainland China    1.0     0.0        0.0

In [54]:
df2 = df.groupby('Country')[['Country','Cases','Deaths','Recovered']].sum().reset_index()
df2

ValueError: cannot insert Country, already exists

In [55]:
df2 = df.groupby('Country', as_index=False)[['Cases', 'Deaths', 'Recovered']].sum()

In [56]:
df2

Country   Cases  Deaths  Recovered
0              Azerbaijan     1.0     0.0        0.0
1             Afghanistan    17.0     0.0        0.0
2                 Algeria    91.0     0.0        0.0
3                 Andorra     7.0     0.0        0.0
4               Argentina    25.0     1.0        0.0
..                    ...     ...     ...        ...
106                    US  2660.0    90.0      150.0
107               Ukraine     6.0     0.0        0.0
108  United Arab Emirates   524.0     0.0      108.0
109          Vatican City     3.0     0.0        0.0
110               Vietnam   560.0     0.0      342.0

[111 rows x 4 columns]

In [57]:
df2.head(50)

Country    Cases  Deaths  Recovered
0               Azerbaijan      1.0     0.0        0.0
1              Afghanistan     17.0     0.0        0.0
2                  Algeria     91.0     0.0        0.0
3                  Andorra      7.0     0.0        0.0
4                Argentina     25.0     1.0        0.0
5                  Armenia      8.0     0.0        0.0
6                Australia    929.0    15.0      327.0
7                  Austria    380.0     0.0        0.0
8               Azerbaijan     42.0     0.0        0.0
9                  Bahrain    649.0     0.0       12.0
10              Bangladesh      3.0     0.0        0.0
11                 Belarus     35.0     0.0        0.0
12                 Belgium    600.0     0.0       21.0
13                  Bhutan      3.0     0.0        0.0
14  Bosnia and Herzegovina     10.0     0.0        0.0
15                  Brazil     65.0     0.0        0.0
16                Bulgaria      4.0     0.0        0.0
17                Cambodia     43.0     0.0       26.0
18                Cameroon      4.0     0.0        0.0
19                  Canada    564.0     0.0       97.0
20                   Chile     22.0     0.0        0.0
21                Colombia      3.0     0.0        0.0
22              Costa Rica      7.0     0.0        0.0
23                 Croatia     96.0     0.0        0.0
24          Czech Republic     99.0     0.0        0.0
25                 Denmark    120.0     0.0        3.0
26      Dominican Republic     14.0     0.0        0.0
27                 Ecuador     82.0     0.0        0.0
28                   Egypt    106.0     1.0       10.0
29                 Estonia     42.0     0.0        0.0
30           Faroe Islands      6.0     0.0        0.0
31                 Finland    126.0     0.0       26.0
32                  France   4411.0    77.0      198.0
33           French Guiana     10.0     0.0        0.0
34                 Georgia     41.0     0.0        0.0
35                 Germany   4316.0     0.0      307.0
36               Gibraltar      5.0     0.0        0.0
37                  Greece    237.0     0.0        0.0
38               Hong Kong   2443.0    54.0      536.0
39                 Hungary     17.0     0.0        0.0
40                 Iceland    225.0     0.0        0.0
41                   India    261.0     0.0       66.0
42               Indonesia     22.0     0.0        0.0
43                    Iran  30003.0  1030.0     7058.0
44                    Iraq    335.0    17.0        0.0
45                 Ireland     72.0     0.0        0.0
46                  Israel    165.0     0.0       14.0
47                   Italy  35041.0  1318.0     2961.0
48             Ivory Coast      1.0     0.0        0.0
49                   Japan   5309.0    76.0      739.0

In [58]:
df2 = df2.orderby('Cases')

AttributeError: 'DataFrame' object has no attribute 'orderby'

In [59]:
df2 = df2.sort_values(by='Cases')

In [60]:
df2

Country      Cases   Deaths  Recovered
0       Azerbaijan        1.0      0.0        0.0
64         Moldova        1.0      0.0        0.0
71   North Ireland        1.0      0.0        0.0
78        Paraguay        1.0      0.0        0.0
48     Ivory Coast        1.0      0.0        0.0
..             ...        ...      ...        ...
75          Others    15692.0     83.0      214.0
43            Iran    30003.0   1030.0     7058.0
47           Italy    35041.0   1318.0     2961.0
96     South Korea    58078.0    362.0      843.0
58  Mainland China  2312052.0  71199.0   780798.0

[111 rows x 4 columns]